CREATE TABLE Usuario
(
    idUsuario      NUMBER(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_usuario   VARCHAR2(60) NOT NULL,
    email_usuario  VARCHAR2(40) UNIQUE NOT NULL,
    senha_usuario  VARCHAR2(10) NOT NULL,
    cargo_usuario  VARCHAR2(30),
    acessibilidade VARCHAR2(50)
);

CREATE TABLE Gestor
(
    idGestor     NUMBER(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_gestor  VARCHAR2(60) NOT NULL,
    email_gestor VARCHAR2(40) UNIQUE NOT NULL,
    senha_gestor VARCHAR2(10) NOT NULL,
    cargo_gestor VARCHAR2(30),
    departamento VARCHAR2(100)
);

CREATE TABLE Tarefa
(
    idTarefa         NUMBER(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idUsuario        NUMBER(2) NOT NULL,
    titulo_tarefa    VARCHAR2(30) NOT NULL,
    descricao_tarefa VARCHAR2(100),
    dataHora_tarefa  TIMESTAMP,
    status_tarefa    VARCHAR2(20),
    CONSTRAINT chk_status_tarefa CHECK (status_tarefa IN ('pendente', 'concluida')),
    CONSTRAINT fk_tarefa_usuario FOREIGN KEY (idUsuario) REFERENCES Usuario (idUsuario)
);

CREATE TABLE Timer
(
    idTimer      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idUsuario    NUMBER NOT NULL,
    tipo_timer   VARCHAR2(20),
    duracao      NUMBER,
    inicio       TIMESTAMP,
    fim          TIMESTAMP,
    status_timer VARCHAR2(20),
    CONSTRAINT chk_tipo_timer CHECK (tipo_timer IN ('foco', 'pausa')),
    CONSTRAINT fk_timer_usuario FOREIGN KEY (idUsuario) REFERENCES Usuario (idUsuario)
);

CREATE TABLE Meta
(
    idMeta         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo_meta    VARCHAR2(50) NOT NULL,
    descricao_meta VARCHAR2(90),
    idUsuario      NUMBER,
    CONSTRAINT fk_meta_usuario FOREIGN KEY (idUsuario) REFERENCES Usuario (idUsuario)
);

CREATE TABLE Lembrete
(
    idLembrete    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idUsuario     NUMBER NOT NULL,
    tipo_lembrete VARCHAR2(50),
    frequencia    NUMBER,
    ativo         CHAR(1) CHECK (ativo IN ('S', 'N')),
    CONSTRAINT fk_lembrete_usuario FOREIGN KEY (idUsuario) REFERENCES Usuario (idUsuario)
);

CREATE TABLE AlertaCrise
(
    idAlertaCrise   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idUsuario       NUMBER NOT NULL,
    idGestor        NUMBER NOT NULL,
    dataHora_alerta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status_alerta   VARCHAR2(20),
    CONSTRAINT chk_status_alerta CHECK (status_alerta IN ('ativo', 'resolvido')),
    CONSTRAINT fk_crise_usuario FOREIGN KEY (idUsuario) REFERENCES Usuario (idUsuario),
    CONSTRAINT fk_crise_gestor FOREIGN KEY (idGestor) REFERENCES Gestor (idGestor)
);